"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['ifttt_key.json', 'app_icon.png']
OPTIONS = {'plist': {'LSUIElement': True}}

setup(
    name="LampControl",
    version="1.0",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
